### ISSUE TITLE
new mod update breaks lists

### ISSUE THREAD

**Issue by fjjghcctjycycy** [coopeeo/customname-geodemod#2]
whatever you did in the new update can't be accessed because it crashes upon being viewed.

[2024-02-21_18-30-03.log](https://github.com/coopeeo/customname-geodemod/files/14363632/2024-02-21_18-30-03.log)
how to access crash:
1. turn on this mod and node ids only
2. view a list. this can be done any way you want.
3. crashes

please fix! :)

**Comment by coopeeo** [comment]
sorry i see that now

**Comment by coopeeo** [comment]
do you have the compact lists mod installed?

**Comment by coopeeo** [comment]
This should be fixed now. Download the latest release from Releases on GitHub.

**Comment by fjjghcctjycycy** [comment]
sorry didnt mean to leave you hanging, just wanted to say i do not use compact lists because it breaks with globed mod :( (idk if that was fixed yet or not)

**Comment by coopeeo** [comment]
yea try latest release on github
